language: r

sudo: required

r_binary_install:
  - XML
  - Rcpp
  - knitr
  - brew
  - RUnit
  - inline
  - highlight
  - formatR
  - highr
  - markdown
  - rgl

r_github_packages:
  - ropensci/RNeXML
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr); coveralls()'
