language: r

sudo: required

r_binary_install:
  - XML
  - Rcpp
  - knitr
  - brew
  - RUnit
  - inline
  - highlight
  - formatR
  - highr
  - markdown
  - rgl
  - testthat

r_check_args: --as-cran

r_github_packages:
  - ropensci/RNeXML
  - fmichonneau/rncl
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr); coveralls()'
