# Project: RcppTemplate

#This include causes many warnings and other issues, and doesn't seem to be needed!
#include $(RHOME)/src/gnuwin32/MkRules

SRC = Rcpp.cpp
OBJ = Rcpp.o
LINKOBJ  = Rcpp.o $(RES)
DLLLIBS = -s -L"$(RHOME)/src/gnuwin32" -lR --no-export-all-symbols --add-stdcall-alias
LIB  = libRcpp.a
CXXFLAGS = -I"$(RHOME)/include" -I"$(RHOME)/src/include" $(CPPFLAGS) -Wall -O2
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before libRcpp.a all-after

clean: clean-custom
	${RM} $(LINKOBJ) $(LIB)

$(OBJ): $(SRC)
	$(CXX) -c $(SRC) -o $(OBJ) $(CXXFLAGS)
	
$(LIB): $(LINKOBJ)
	ar r $(LIB) $(OBJ)
	ranlib $(LIB)
	rm $(OBJ)
