# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

isLabelName <- function(lblToCheck, lbl) {
    .Call(`_phylobase_isLabelName`, lblToCheck, lbl)
}

nRoots <- function(ances) {
    .Call(`_phylobase_nRoots`, ances)
}

tabulateTips <- function(ances) {
    .Call(`_phylobase_tabulateTips`, ances)
}

nTipsSafe <- function(ances) {
    .Call(`_phylobase_nTipsSafe`, ances)
}

nTipsFastCpp <- function(ances) {
    .Call(`_phylobase_nTipsFastCpp`, ances)
}

hasSingleton <- function(ances) {
    .Call(`_phylobase_hasSingleton`, ances)
}

hasPolytomy <- function(ances) {
    .Call(`_phylobase_hasPolytomy`, ances)
}

tipsSafe <- function(ances, desc) {
    .Call(`_phylobase_tipsSafe`, ances, desc)
}

tipsFast <- function(ances) {
    .Call(`_phylobase_tipsFast`, ances)
}

getAllNodesSafe <- function(edge) {
    .Call(`_phylobase_getAllNodesSafe`, edge)
}

getAllNodesFast <- function(edge) {
    .Call(`_phylobase_getAllNodesFast`, edge)
}

testEqInt <- function(x, y) {
    .Call(`_phylobase_testEqInt`, x, y)
}

all_naC <- function(x) {
    .Call(`_phylobase_all_naC`, x)
}

any_naC <- function(x) {
    .Call(`_phylobase_any_naC`, x)
}

nb_naC <- function(x) {
    .Call(`_phylobase_nb_naC`, x)
}

getRange <- function(x, na_rm) {
    .Call(`_phylobase_getRange`, x, na_rm)
}

hasDuplicatedLabelsCpp <- function(label) {
    .Call(`_phylobase_hasDuplicatedLabelsCpp`, label)
}

edgeIdCpp <- function(edge, type) {
    .Call(`_phylobase_edgeIdCpp`, edge, type)
}

checkTreeCpp <- function(obj, opts) {
    .Call(`_phylobase_checkTreeCpp`, obj, opts)
}

