##

SRC = nxsassumptionsblock.cpp nxsdistancedatum.cpp   nxsstring.cpp \
nxsblock.cpp             nxsdistancesblock.cpp  nxstaxablock.cpp \
nxscharactersblock.cpp        nxstoken.cpp \
nxsdatablock.cpp         nxsexception.cpp       nxstreesblock.cpp \
nxsdiscretedatum.cpp     nxsreader.cpp          nxsunalignedblock.cpp \
nxsdiscretematrix.cpp    nxssetreader.cpp

## nxsemptyblock.cpp 

OBJ = nxsassumptionsblock.o nxsdistancedatum.o   nxsstring.o \
nxsblock.o             nxsdistancesblock.o  nxstaxablock.o \
nxscharactersblock.o   nxstoken.o \
nxsdatablock.o         nxsexception.o       nxstreesblock.o \
nxsdiscretedatum.o     nxsreader.o          nxsunalignedblock.o \
nxsdiscretematrix.o    nxssetreader.o

LINKOBJ = $(OBJ) $(RES)

DLLLIBS = -s  --no-export-all-symbols --add-stdcall-alias
LIB  = libncl.a
CXXFLAGS = $(CPPFLAGS) -Wall -O2
RM = rm -f
	
.PHONY: all all-before all-after clean clean-custom

all: all-before libncl.a  all-after

clean: clean-custom
	${RM} $(LINKOBJ) $(LIB)

$(OBJ): $(SRC)
	$(CXX) -c $*.cpp -o $*.o $(CXXFLAGS)
	
$(LIB): $(LINKOBJ)
	ar r $(LIB) $(OBJ)
	ranlib $(LIB)
	rm $(OBJ)

